name: raffle_fox
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  bitsdojo_window: ^0.1.6
  grouped_list: ^6.0.0
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  smooth_page_indicator: ^1.2.0+3
  responsive_grid_list: ^1.4.0
  flutter_dash: ^1.0.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_analytics: ^11.3.5
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0 
  firebase_messaging: ^15.1.5
  image_picker: ^1.0.4
  intl: ^0.19.0
  provider: ^6.1.2
  url_launcher: ^6.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^4.3.0
  string_similarity: ^2.1.1
  fuzzy: ^0.5.1
  intl_phone_field: ^3.2.0
  country_code_picker: ^3.1.0
  flutter_launcher_icons: ^0.14.1
  firebase_admin: ^0.3.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_native_splash: ^2.4.3
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.0.14
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.jpeg"

flutter: 
  uses-material-design: true
  assets: 
   

    - assets/images/
    - assets/images/Button.svg
    - assets/images/vector.svg
    - assets/images/details.png
    - assets/images/img_group_1000004681.svg
    - assets/images/img_button.svg
    - assets/images/img_vector_1.svg
    - assets/images/img_image.png
    - assets/images/img_group_1000004660.svg
    - assets/images/img_ellipse.svg
    - assets/images/raffleFox.jpeg

flutter_native_splash:
  color: "#ffffff" # Background color (white in this case)
  image: assets/images/splash.png
  android: true
  ios: true
  web: false # Set to true if building for web
  fullscreen: true 
 

  
